services:
  postgres:
    image: postgres:17
    container_name: entregas-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: motonote
      POSTGRES_PASSWORD: motonote
      POSTGRES_DB: motonote
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
